---
title: "Vowel duration and first formant frequency: Data from North-Western Italian"
author: "Stefano Coretta"
format:
  html:
    number-sections: true
  pdf:
    number-sections: true
bibliography: refs.bib
---

# Introduction

# Methods

The data used in this study come from a study which focussed on durational properties of voiced intervals in Italian.
Both audio and electroglottographic recordings were made in the original study.
This study is based on the audio recordings only.

## Participants

A total of 19 native speakers of Italian participated in the study (median age = 42, age range = 18-59; 15 women).
The inclusion criteria were being a native speaker of Italian from the VCO province (Italy), 18 years old or more, with no reported hearing or speaking disorders, with normal or corrected to normal vision.

## Procedure

The participants were while reading sentences including CVCo target words presented on a computer screen with PsychoPy [@peirce2009], in a quiet room in Verbania (the county seat of the VCO province, Italy).
Time-synchronised audio and electroglottographic data was collected using a Glottal Enterprises EG2-PCX2 electroglottograph and a RØDE Lavalier microphone, at a sample rate of 44100 Hz (16-bit; downsampled to 22050 Hz for analysis).
The acquisition of the signals was controlled with Audacity running on a MacBook Pro (Retina, 13-inch, Mid 2014).
The recordings will be subject to force alignment with ... for analysis in Praat [@boersma2018].

## Materials

Target words were created according to the form /CVCo/, with primary stress on the first syllable, using all permutations of C = /p, t, k/ and V = /i, e, a, ɔ, u/.
The choice of segments was constrained by the research question of the original study which was on the voiced interval between the two voiceless consonants of the target words.
Due to this, the target words contain voiceless stops only.
Only 5 vowel were included due to the restriction of the second consonant being a singleton.^[While Standard Italian is commonly described as having a 7-vowel system, in reality the low-mid/high-mid distinction is very marginally contrastive in many spoken varieties of Italian [@renwick2016]. In the variety of Italian spoken in the VCO province, /e-ɛ/ tends to be [e] in open syllables and [ɛ] in closed ones, while /o-ɔ/ tends to be [ɔ] in open syllables and [o] in closed ones (i.e. /e-ɛ/ and /o-ɔ/ have opposite patterns): e.g. *sete* /sete/ [seːte] ~ *sette* /sette/ [sɛtte], *foto* /foto/ [fɔːto] 'photo' ~ *fotto* /fotto/ [fotto] 'I steal'.]
In open stressed syllables, vowels tend to have longer duration in Italian, duration not being a distinctive feature (in mainstream analyses that assume stress position to be): e.g. *cheto* /ˈketo/ [ˈkeːto] 'quiet'.
This makes the first vowel in the target words long.
Note that all the analyses were run on the (stressed) first vowel in the target words (i.e. the target vowel).

[Insert words table]

The following frame sentences were used (where *X* is the CVCo target word): *Scrivete X sul foglio* 'Write X on the sheet', *Ha detto X sei volte* 'S/he said X six times', *Sentivo X di nuovo* 'I heard X again', *Ripete X da sempre* 'S/he's repeating X since always'.

## Data processing

Formant measurements were obtained using the Fast Track plugin [@barreda2021] in Praat [@boersma2018].
For each vowel, the median (or average) formant values for the first three formants were collected for each of five intervals (0-20, 20-40, 40-60, 60-80, 80-100%).
All subsequent analyses are based on the median value taken from the central interval (40-60%).

## Data analysis

[Note about using group-level effects instead of z-scoring formants in the data].
[Note about 90% CrIs].

# Results

## Linear modelling

I fitted a Bayesian linear model using a Gaussian distribution with standardised logged vowel duration as the outcome variable and the following predictors: vowel quality (`a, e, i , o, u`), standardized F1 (*z*-scores), an interaction between vowel quality and F1, a group-level (aka random) intercept by speaker and group-level slopes for vowel, F1 and their interaction by speaker. In R syntax: `brm(duration_logz ~ vowel + f13_z + vowel:f13_z + (vowel + f13_z + vowel:f13_z | speaker), family = gaussian)`.
The use of a Gaussian distribution with logged values is equivalent to the use of a log-normal distribution.
This is appropriate with segment duration values, since they are bounded to positive numbers (i.e. they can't be negative).
The following weakly informative priors were used: ...

According to the model, the direct effect of F1 on vowel duration (for an average vowel) is an increase between +0.28 and +0.45 standard units of logged duration at 90% confidence (0.37, SD = 0.05) for every standard unit increase of F1.
In other words, higher F1 values correspond to longer vowel duration.
However, the direct effect of F1 is not sufficient to explain vowel duration: vowel quality exercises an additional direct effect on vowel duration.
This additional effect is robust in each vowel, given that the very narrow 90% CrIs  which contain only positive or negative values ().

Moreover, the direct effect of F1 on vowel duration is modulated by vowel quality.
According to the model, the predicted 90% CrI of the F1 effect on vowel duration for each vowel is (from largest to smallest) [0.58, 0.88] for /a/, [0.32, 0.67] for /e/, [0.16, 0.56] for /ɔ/, [0.22, 0.42] for /i/ and [-0.2, 0.1] for /u/.
All vowels except /u/ show a robust positive effect of F1 on vowel duration.
The effect of /u/ is much more uncertain, with both negative and positive values, although the 90% CrI covers double the negative values perhaps suggesting a small negative effect.



# References

::: {#refs}
:::
